### ISSUE TITLE
Bouton dédié dans la Wikibarre

### ISSUE THREAD

**Issue by jemattarde** [franck-paul/bigfoot#2]
Déjà bravo pour le rendu car je trouve les infobulles pratiques et ludiques. Va falloir trouver le bon usage cependant , c’est à dire un usage avec parcimonie.

Dans l’idéal, ce serait super qu’un bouton de la wikibarre lui soit dédié afin de faciliter leur intégration dans le contenu des billets. Sauf si j’ai manqué quelque chose, leur implémentation ne se fait qu’en édition HTML avec les lignes de code expliquées ici : [plugin bigfoot](https://open-time.net/post/2016/02/04/Plugin-bigfoot-03-pour-Dotclear) 

Bel été

**Comment by franck-paul** [comment]
Euh non, pas du tout. Il suffit d'insérer des notes de bas de page, que ce soit en wiki ou en markdown pour qu'elles soient gérées par le plugin. Nul besoin d'un bouton supplémentaire, tout se fait côté public.
